// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebpToolkit
{
    internal sealed partial class Vsix
    {
        public const string Id = "WebpToolkit.3c6bbdde-9aa2-4b8a-b6e8-732cf3bfac87";
        public const string Name = "WebP Toolkit";
        public const string Description = @"Enhances WebP support in Visual Studio, including the ability to generate of  WebP files from existing image files.";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "Kyle Herzog";
        public const string Tags = "WebP, optimization, image, generate, picture, img";
    }
}
