// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WebpToolkit
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidWebpGeneratorPkgString = "d750f405-251d-41d3-935b-13dac84d69ed";
        public static Guid guidWebpGeneratorPkg = new Guid(guidWebpGeneratorPkgString);

        public const string guidWebpGeneratorCmdSetString = "ecbf1e9a-1026-43bc-89d1-b429e74f70bf";
        public static Guid guidWebpGeneratorCmdSet = new Guid(guidWebpGeneratorCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenu = 0x1010;
        public const int MyMenuGroup = 0x1020;
        public const int GeneratorGroup = 0x2000;
        public const int cmdGenerateLossy = 0x0100;
        public const int cmdGenerateLossless = 0x0150;
    }
}